# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XxMK9DIO_70Ygvswoz96WPVfdgwKtAyi
"""

import sqlite3

conn = sqlite3.connect(":memory:")
cursor = conn.cursor()

cursor.execute('''
    CREATE TABLE IF NOT EXISTS people (
        Id INTEGER PRIMARY KEY,
        Name TEXT NOT NULL,
        Age INTEGER NOT NULL,
        Job TEXT NOT NULL
    )
''')

cursor.executemany('''
    INSERT INTO people (Id, Name, Age, Job) VALUES (?, ?, ?, ?)
''', [
    (1, 'Alan', 11, 'Unemployed'),
    (2, 'Bob', 22, 'Gamer'),
    (3, 'Chuck', 33, 'Farmer'),
    (4, 'Dave', 44, 'Painter'),
    (5, 'Ed', 55, 'Writer'),
    (6, 'Fred', 66, 'Writer'),
    (7, 'Greg', 77, 'Writer'),
    (8, 'Hank', 88, 'Retired'),
    (9, 'Ike', 99, 'Retired')
])

cursor.execute('''
    CREATE TABLE IF NOT EXISTS income (
        Job TEXT PRIMARY KEY,
        Income INTEGER NOT NULL
    )
''')

cursor.executemany('''
    INSERT INTO income (Job, Income) VALUES (?, ?)
''', [
    ('None', 0),
    ('Farmer', 200000),
    ('Painter', 100000),
    ('Writer', 50000),
    ('Retired', 0),
    ('Baker', 80000)
])

query = '''
    SELECT Name FROM people
    WHERE Job IN (SELECT Job FROM income WHERE Income > 50000)
'''
cursor.execute(query)
result = cursor.fetchall()

print("收入超过 50,000 的人的姓名:")
for row in result:
    print(row[0])

conn.close()